export default {
  products: [
    {
      _id: '1',
      name: 'Tavolino "TAB.U" diametro 30cm',
      category: 'furniture',
      image: '/images/01.JPG',
      price: 366,
      brand: 'OPINION CIATTI',
      rating: 3.0,
      numReviews: 3,
      countInStock: 2,
    },
    {
      _id: '2',
      name: '4 Sedie "HIGHFRAME"',
      category: 'furniture',
      image: '/images/02.JPG',
      price: 1213,
      brand: 'ALIAS',
      rating: 4.0,
      numReviews: 7,
      countInStock: 4,
    },
    {
      _id: '3',
      name: 'Tavolino "SWISS" diametro 55',
      category: 'furniture',
      image: '/images/03.JPG',
      price: 680,
      brand: 'DEPADOVA',
      rating: 3.5,
      numReviews: 5,
      countInStock: 3,
    },
    {
      _id: '4',
      name: '4 Sedie "SPOLETO"',
      category: 'furniture',
      image: '/images/04.JPG',
      price: 3490,
      brand: 'KNOLL',
      rating: 4.5,
      numReviews: 6,
      countInStock: 2,
    },
    {
      _id: '5',
      name: 'Panca "FLORENCE"',
      category: 'furniture',
      image: '/images/05.JPG',
      price: 3520,
      brand: 'KNOLL',
      rating: 5.0,
      numReviews: 2,
      countInStock: 1,
    },
    {
      _id: '6',
      name: 'Tavolino "PALAFITTE" diametro 65cm',
      category: 'furniture',
      image: '/images/06.JPG',
      price: 492,
      brand: 'MEDULUM',
      rating: 2.5,
      numReviews: 2,
      countInStock: 1,
    },
  ],
};
